### ISSUE TITLE
"Serialization of 'Closure' is not allowed" When using Webhook with automation

### ISSUE THREAD

**Issue by CupNoodles** [igniter-labs/ti-ext-webhook#5]
**Expected behavior:**
After installing both the automation and webhook plugins, there's an option for a webhook event called "Send payload to Webhooks". Using this option with any URL+secret causes the error message to be logged to 'recent failures' of the automation event. 

**Actual behavior:**
First line of the traceback is `/var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(158): serialize(Object(Spatie\WebhookServer\CallWebhookJob)) ` which is odd because at first glance, `Spatie\WebhookServer\CallWebhookJob` does appear to be Queuable.

**Reproduce steps:**
Install both plugins and set up an automation event to trigger on Order Creation. 

Put any url into the URL field of the 'Send Payload to webhooks' form.

Create an order.

Check 'Recent Failures' tab on your automation event.

**Version:**
TI version 3.1.2
PHP 8.0.12

**Comment by PlumbBum** [comment]
Bump - any solultion to this? Currently experiencing the same ATM.

**Comment by sampoyigi** [comment]
Thanks for bumping, somehow missed @CupNoodles's comment. Its been fixed now with a new update released!
